language: php
sudo: false
php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm
  - nightly
matrix:
  allow_failures:
    - php: nightly
    - php: hhvm
before_install:
  - composer selfupdate
install:
  - composer install --no-interaction --prefer-source
script:
  - ./bin/phpunit
notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/1e1d3686ffbd143cedd7
    on_success: always
    on_failure: always
    on_start: never
